"""Aggregate the Phase 3 baseline runs into results/baselines/phase3_report.txt.

Reads only run_config.yaml and metrics.json from each completed run directory.
Every number in the report comes from those files -- nothing is recomputed from
memory and nothing is estimated. Runs whose config still says STARTED are
skipped and named, so a partial sweep cannot quietly be reported as a full one.

The headline question this answers is the F4 gate in architecture_spec.md
4.1.4: does the TRAINED memory horizon approach TAD scale (100 kb+)? If it does
not, conditioning on TAD-scale structure is not expressible at this model size
and Phase 4 must be re-scoped before it spends compute.

Run:  python scripts/phase3_report.py
"""

from __future__ import annotations

import json
import math
import statistics as stats
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
RESULTS = REPO / "results" / "baselines"
OUT = RESULTS / "phase3_report.txt"

TAD_TOKENS = 100_000        # 100 kb, the low end of TAD scale
BIN_TOKENS = 5_000          # one Hi-C bin at the pilot's 5 kb resolution
VALIDATED_TAD = 385_000     # the TAD confirmed in data_card.md 4B.2


def fmt(x, nd=4):
    return "n/a" if x is None else f"{x:.{nd}f}"


def mean_sd(vals):
    if not vals:
        return None, None
    if len(vals) == 1:
        return vals[0], 0.0
    return stats.mean(vals), stats.stdev(vals)


def load_runs(prefix="baseline_seed"):
    runs = []
    for d in sorted(RESULTS.glob(f"{prefix}*")):
        cfg_p, met_p = d / "run_config.yaml", d / "metrics.json"
        if not cfg_p.exists() or not met_p.exists():
            continue
        cfg = yaml.safe_load(cfg_p.read_text())
        met = json.loads(met_p.read_text())
        runs.append({"dir": d, "cfg": cfg, "metrics": met,
                     "status": cfg.get("status", "UNKNOWN")})
    return runs


def main() -> int:
    runs = load_runs()
    if not runs:
        print(f"No runs found under {RESULTS}. Nothing to report.")
        return 1

    done = [r for r in runs if r["status"] == "COMPLETED"]
    partial = [r for r in runs if r["status"] != "COMPLETED"]

    L = []
    w = L.append
    w("=" * 78)
    w("PHASE 3 -- SEQUENCE-ONLY BASELINE: RESULT")
    w("=" * 78)
    w("")
    w("Generated by scripts/phase3_report.py from results/baselines/*/metrics.json")
    w("and run_config.yaml. No number here was typed by hand.")
    w("")

    if partial:
        w("!! RUNS FOUND THAT DID NOT COMPLETE -- excluded from every number below:")
        for r in partial:
            w(f"     {r['dir'].name}  status={r['status']}")
        w("")
    if not done:
        w("NO COMPLETED RUNS. Nothing can be reported.")
        OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
        print("\n".join(L))
        return 1

    c0 = done[0]["cfg"]

    # ---------------- provenance ----------------
    w("-" * 78)
    w("1. PROVENANCE")
    w("-" * 78)
    g, e = c0["git"], c0["environment"]
    w(f"  git commit         {g['commit']}  (branch {g['branch']})")
    w(f"  working tree dirty {g['dirty']}")
    if g.get("dirty_files"):
        for f in g["dirty_files"]:
            w(f"                     M {f}")
    w(f"  python             {e['python']}")
    w(f"  torch              {e['torch']}  (cuda build {e['torch_cuda_build']})")
    w(f"  triton             {e['triton']}")
    w(f"  numpy              {e['numpy']}")
    w(f"  nvidia kernel mod  {e['nvidia_kernel_module']}")
    w(f"  nvidia-smi         {e['nvidia_smi']}")
    for gp in e["gpus"]:
        w(f"  gpu{gp['index']}               {gp['name']}  cc{gp['capability']}  "
          f"{gp['total_memory_GiB']} GiB")
    sb = c0["scan_backend"]
    w(f"  scan backend       {sb['backend']}")
    w(f"  kernel validation  {sb['validated_by']}")
    w(f"  bitwise reproducible {sb['bitwise_reproducible']}  -- {sb['bitwise_note']}")
    w(f"  precision          {c0['precision']['dtype']}, "
      f"autocast={c0['precision']['autocast']}")
    w("")

    # ---------------- setup ----------------
    w("-" * 78)
    w("2. SETUP")
    w("-" * 78)
    h, eb, m, dd = (c0["hyperparameters"], c0["effective_batch"],
                    c0["masking"], c0["data"])
    w(f"  model              BiMambaLM(structural=False), "
      f"{c0['model']['n_parameters']:,} parameters")
    w(f"                     d_model={c0['model']['d_model']} "
      f"n_layer={c0['model']['n_layer']} d_state={c0['model']['d_state']} "
      f"d_inner={c0['model']['d_inner']}")
    w(f"  optimiser steps    {h['steps']}")
    w(f"  windows/step       {eb['windows_per_optimizer_step']} "
      f"({eb['tokens_per_optimizer_step']:,} tokens)")
    w(f"  ddp backend        {eb['ddp_backend']}  world_size={eb['world_size']}")
    w(f"  lr                 {h['lr']}, warmup {h['warmup_steps']}, "
      f"cosine to {h['lr_final_frac']}x")
    w(f"  weight decay       {h['weight_decay']} (none on norms, biases, A_log, D)")
    w(f"  masking            {m['mask_prob']} of ACGT; "
      f"{m['p_mask']}/{m['p_random']}/{m['p_keep']} mask/random/keep")
    w(f"                     {m['excluded']}")
    w(f"  rc augmentation    {h['rc_augment']}")
    w(f"  train windows      {dd['n_train_windows']:,}   "
      f"val windows {dd['n_val_windows']:,}   window {dd['window']:,} bp")
    w(f"  seeds              {[r['cfg']['seed'] for r in done]}")
    w("")

    # ---------------- per-seed results ----------------
    w("-" * 78)
    w("3. RESULT PER SEED  (final eval, lower is better; uniform floor = 2.000)")
    w("-" * 78)
    w(f"  {'seed':>4}  {'val bits/nt':>12}  {'val acc':>8}  "
      f"{'train bits/nt':>13}  {'wall clock':>11}")
    finals = []
    for r in done:
        ev = [x for x in r["metrics"] if "val_bits_per_nucleotide" in x]
        last = ev[-1]
        finals.append(last)
        w(f"  {r['cfg']['seed']:>4}  {last['val_bits_per_nucleotide']:>12.4f}  "
          f"{last['val_accuracy']:>8.4f}  "
          f"{last['train_bits_per_nucleotide']:>13.4f}  "
          f"{r['cfg'].get('wall_clock_s', 0)/3600:>10.2f}h")
    vb = [f["val_bits_per_nucleotide"] for f in finals]
    va = [f["val_accuracy"] for f in finals]
    mb, sb_ = mean_sd(vb)
    ma, sa = mean_sd(va)
    w("")
    w(f"  across {len(done)} seeds:")
    w(f"    val bits/nucleotide   mean {mb:.4f}   sd {sb_:.4f}   "
      f"min {min(vb):.4f}   max {max(vb):.4f}")
    w(f"    val accuracy          mean {ma:.4f}   sd {sa:.4f}")
    w(f"    uniform-random floor  2.0000 bits (4 nucleotides, N excluded)")
    w(f"    improvement on floor  {2.0 - mb:.4f} bits")
    w("")
    w("  This sd is the sigma_real that architecture_spec.md 4.1.3 uses as the")
    w("  2*sigma effect-size floor for the Phase 4 shuffled-structure gate.")
    w("")

    # ---------------- tau ----------------
    w("-" * 78)
    w("4. MEMORY HORIZON tau  -- THE PHASE 4 GATE (architecture_spec.md 4.1.4 F4)")
    w("-" * 78)
    w("  tau = 1 / (Delta * |A|), in tokens; 1 token = 1 bp.")
    w("")
    w("  Two measurements, and they are NOT interchangeable:")
    w("    bias-only  tau from dt_proj.bias alone -- BiMambaLM.tau_stats(). Fair")
    w("               at init, unreliable once trained, because Delta is then")
    w("               dominated by the input-dependent term W_dt delta'_t.")
    w("    empirical  tau from the Delta the model actually produces on real")
    w("               validation batches. THIS is what the gate is read from.")
    w("")

    init_tau = c0["tau_at_init_bias_only"]
    init_max = max(v["tau_max"] for v in init_tau.values())
    init_med = stats.median([v["tau_median"] for v in init_tau.values()])
    w(f"  AT INITIALISATION (bias-only, from run_config.yaml):")
    w(f"    tau median {init_med:>12.1f} tokens")
    w(f"    tau max    {init_max:>12.1f} tokens")
    w("")

    keys = ["tau_median", "tau_p90", "tau_p99", "tau_max",
            "frac_ge_5k", "frac_ge_100k"]
    trained = {k: [] for k in keys}
    relayed = []
    trained_bias_max = []
    for r in done:
        ev = [x for x in r["metrics"] if "tau_empirical" in x]
        if not ev:
            continue
        s = ev[-1]["tau_empirical"]["summary"]
        for k in keys:
            trained[k].append(s[k])
        relayed.append(s["relayed_sum_layer_tau_max_fwd"])
        if "tau_bias_only" in ev[-1]:
            trained_bias_max.append(
                max(v["tau_max"] for v in ev[-1]["tau_bias_only"].values()))

    w(f"  AFTER TRAINING (empirical, mean +/- sd over {len(trained['tau_max'])} seeds):")
    for k, label in (("tau_median", "median"), ("tau_p90", "p90"),
                     ("tau_p99", "p99"), ("tau_max", "max")):
        mu, sd = mean_sd(trained[k])
        w(f"    tau {label:<7} {mu:>14,.1f} +/- {sd:>10,.1f} tokens")
    mu5, sd5 = mean_sd(trained["frac_ge_5k"])
    mu100, sd100 = mean_sd(trained["frac_ge_100k"])
    w(f"    fraction of (position, channel, state) triples with:")
    w(f"      tau >= {BIN_TOKENS:,} tokens (one 5 kb Hi-C bin)   "
      f"{mu5:.6f} +/- {sd5:.6f}")
    w(f"      tau >= {TAD_TOKENS:,} tokens (100 kb, TAD scale)  "
      f"{mu100:.6f} +/- {sd100:.6f}")
    mur, sdr = mean_sd(relayed)
    w(f"    relayed across 16 layers (sum of per-layer fwd tau_max, a HEURISTIC")
    w(f"    and not a bound): {mur:,.1f} +/- {sdr:,.1f} tokens")
    if trained_bias_max:
        mbm, sbm = mean_sd(trained_bias_max)
        w("")
        w(f"    for contrast, bias-only tau max after training: "
          f"{mbm:,.1f} +/- {sbm:,.1f} tokens")
        w(f"    (logged because the runbook asks for tau_stats(); the gap against")
        w(f"     the empirical number above is exactly why the gate uses empirical)")
    w("")

    # ---------------- the verdict ----------------
    tmax_mu, _ = mean_sd(trained["tau_max"])
    w("-" * 78)
    w("5. DOES TRAINED tau APPROACH TAD SCALE?")
    w("-" * 78)
    w(f"  single-layer tau_max        {tmax_mu:,.1f} tokens")
    w(f"  one 5 kb Hi-C bin           {BIN_TOKENS:,} tokens   "
      f"-> ratio {tmax_mu/BIN_TOKENS:.3f}")
    w(f"  100 kb (low end of TAD)     {TAD_TOKENS:,} tokens   "
      f"-> ratio {tmax_mu/TAD_TOKENS:.4f}")
    w(f"  385 kb (the validated TAD)  {VALIDATED_TAD:,} tokens   "
      f"-> ratio {tmax_mu/VALIDATED_TAD:.4f}")
    w(f"  relayed 16-layer heuristic  {mur:,.1f} tokens   "
      f"-> {mur/TAD_TOKENS:.4f} of 100 kb")
    w("")
    reaches_bin = tmax_mu >= BIN_TOKENS
    reaches_tad = tmax_mu >= TAD_TOKENS
    relay_reaches_tad = mur >= TAD_TOKENS
    w(f"  single-layer tau_max reaches one Hi-C bin (5 kb)?   {reaches_bin}")
    w(f"  single-layer tau_max reaches TAD scale (100 kb)?    {reaches_tad}")
    w(f"  relayed heuristic reaches TAD scale (100 kb)?       {relay_reaches_tad}")
    w(f"  any (channel,state) mass at TAD scale?              "
      f"{mu100 > 0} (fraction {mu100:.6f})")
    w("")
    w("  VERDICT:")
    if reaches_tad or (relay_reaches_tad and mu100 > 0):
        w("    Trained tau DOES approach TAD scale. The architecture can express")
        w("    dependencies at the scale mechanism (a) conditions on. Proceed to")
        w("    Phase 4 as specified in architecture_spec.md 4.1.")
    else:
        w("    Trained tau does NOT approach TAD scale.")
        w("")
        w("    Per the decision table in architecture_spec.md 4.1.4 F4, the action")
        w("    is: re-scope to sub-TAD structural signal, or raise d_model/d_state,")
        w("    BEFORE spending Phase 4 compute -- not after.")
        w("")
        w("    Read this carefully, because it is a statement about the BACKBONE,")
        w("    not about the structural mechanism. The limit applies identically to")
        w("    the baseline and to the structural arm: a model that cannot carry")
        w("    information 100 kb cannot be helped by being told where the TAD")
        w("    boundaries at that scale are. It does not say structure is useless")
        w("    -- phi also carries sub-TAD signal (insulation at 100 kb windows is")
        w("    a per-bin quantity, and the interpolated s_t varies at every")
        w("    position) -- it says the TAD-scale framing of the claim is not")
        w("    supportable at this model size.")
    w("")

    # ---------------- convergence trace ----------------
    w("-" * 78)
    w("6. CONVERGENCE TRACE  (val bits/nucleotide by step, per seed)")
    w("-" * 78)
    steps = [x["step"] for x in done[0]["metrics"] if "val_bits_per_nucleotide" in x]
    w("  step   " + "".join(f"seed{r['cfg']['seed']:<8}" for r in done))
    for i, st in enumerate(steps):
        row = f"  {st:<6} "
        for r in done:
            ev = [x for x in r["metrics"] if "val_bits_per_nucleotide" in x]
            row += f"{ev[i]['val_bits_per_nucleotide']:<12.4f}" if i < len(ev) else "-           "
        w(row)
    w("")
    w("-" * 78)
    w("7. WHAT THIS RUN DOES NOT ESTABLISH")
    w("-" * 78)
    w("  * One chromosome, one cell line, one species (data_card.md 5).")
    w("  * Splits are within chr9, not across chromosomes, so held-out numbers")
    w("    are optimistic relative to CHROME's chr9-held-out design.")
    w("  * Training windows overlap 50%: the ~5,422 windows cover about 89 Mb of")
    w("    unique sequence, not 178 Mb. Quote unique coverage for tokens seen.")
    w("  * No structural arm exists yet. Nothing here compares anything to")
    w("    anything; it establishes the floor the Phase 4 comparison is measured")
    w("    against, and the sigma_real that its effect-size gate needs.")
    w("=" * 78)

    text = "\n".join(L) + "\n"
    OUT.write_text(text, encoding="utf-8")
    print(text)
    print(f"written to {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
